name: blue_tine_web_components
description: "A new Flutter project."
publish_to: 'none'


version: 1.0.0+1


environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter

  # Web Components
  webview_flutter: ^4.10.0

  # Base-App
  hive_flutter: ^1.1.0
  flutter_bloc: ^8.1.6
  intl: ^0.19.0
  flex_color_scheme: ^7.3.1
  settings_ui: ^2.0.2
  syncfusion_flutter_calendar: ^27.1.53
  circular_countdown_timer: ^0.2.0
  flutter_rating_bar: ^4.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  dependency_validator: ^4.1.0
  build_runner: ^2.1.10
  hive_generator: ^2.0.0


flutter:
  uses-material-design: true